Factory/Models/Machine.cs
using System.Collections.Generic;

namespace Factory.Models
{
    public class Machine
    {
        public Machine()
        {
            this.Engineers = new HashSet<EngineerMachine>();
        }

        public int MachineId { get; set; }
        public string MachineName { get; set; }

        public ICollection<EngineerMachine> Engineers { get;}
    }
}

Factory/Controllers/MachineController.cs
using Microsoft.AspNetCore.Mvc;
using Factory.Models;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Factory.Controllers
{
    public class MachinesController : Controller
    {
        private readonly FactoryContext _db;

        public MachinesController(FactoryContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Machines.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Machine machine, int EngineerId)
        {
            _db.Machines.Add(machine);
            if (EngineerId != 0)
            {
                _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisMachine = _db.Machines
                .Include(machine => machine.Engineers)
                .ThenInclude(join => join.Engineer)
                .FirstOrDefault(machine => machine.MachineId == id);
            return View(thisMachine);
        }

        public ActionResult Edit(int id)
        {
            var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
            return View(thisMachine);
        }

        [HttpPost]
        public ActionResult Edit(Machine machine, int EngineerId)
        {
            if (EngineerId != 0)
            {
                _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
            }
            _db.Entry(machine).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult AddEngineer(int id)
        {
            var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
            ViewBag.EngineerId = new SelectList(_db.Engineers, "EngineerId", "EngineerName");
            return View(thisMachine);
        }

        [HttpPost]
        public ActionResult AddEngineer(Machine machine, int EngineerId)
        {
            if (EngineerId != 0)
            {
                _db.EngineerMachine.Add(new EngineerMachine() { EngineerId = EngineerId, MachineId = machine.MachineId });
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
            return View(thisMachine);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisMachine = _db.Machines.FirstOrDefault(machines => machines.MachineId == id);
            _db.Machines.Remove(thisMachine);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteEngineer(int joinId)
        {
            var joinEntry = _db.EngineerMachine.FirstOrDefault(entry => entry.EngineerMachineId == joinId);
            _db.EngineerMachine.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Factory/Views/Machines/AddEngineer.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add an Engineer</h2>
<hr/>
<h4>Assign an Engineer to this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.Label("Select Engineer")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" class="btn btn-primary" />
}
<hr/>
<p>@Html.ActionLink("Back To Machine List", "Index", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>

Factory/Views/Machines/Create.cshtml
@{
  Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Add a New Machine:</h2>
<hr/>
@using (Html.BeginForm())
{
    <h4>Machine Name: @Html.TextBoxFor(model => model.MachineName)</h4>
    

    @Html.Label("Assign an engineer:")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Add new Machine" class="btn btn-primary" />
}
<hr/>
<p>@Html.ActionLink("Show All Machines", "Index", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>

Factory/Views/Machines/Delete.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Are you sure you want to remove this Machine?</h2>
<hr/>
<h3>Machine Name: @Html.DisplayFor(model => model.MachineName)</h3>
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-danger" />
}
<hr/>
<p>@Html.ActionLink("Back to Machine List", "Index", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>

Factory/Views/Machines/Details.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Machine Details</h2>
<hr />
<h3>Machine Name: @Html.DisplayFor(model => model.MachineName)</h3>
<hr/>
@if(@Model.Engineers.Count == 0)
{
  <p>There are no engineers assigned to this machine.</p>
}
else
{
    <h4>Engineers assigned to this machine:</h4>

    @foreach(var join in Model.Engineers)
    {
        @join.Engineer.EngineerName
        @using (Html.BeginForm("DeleteEngineer", "Machines"))
        {
            @Html.Hidden("joinId", @join.EngineerMachineId)
            <input type="submit" value="Delete" class="btn btn-warning"/>
        }
    }
}
<hr/>
<p>@Html.ActionLink("Back to Machine List", "Index", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Edit Machine", "Edit", new { id = Model.MachineId }, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Add an Engineer", "AddEngineer", new { id = Model.MachineId }, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Delete Machine", "Delete", new { id = Model.MachineId }, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>

Factory/Views/Machines/Edit.cshtml
@{
    Layout = "_Layout";
}

@model Factory.Models.Machine

<h2>Edit Machine</h2>
<hr/>
<h4>Edit this Machine: @Html.DisplayFor(model => model.MachineName)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.MachineId)

    @Html.LabelFor(model => model.MachineName)
    @Html.EditorFor(model => model.MachineName)

    @Html.Label("Select a Engineer to assign to this machine")
    @Html.DropDownList("EngineerId")

    <input type="submit" value="Save" class="btn btn-primary" />
}
<hr/>
<p>@Html.ActionLink("Back to Machine List", "Index", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>

Factory/Views/Machines/Index.cshtml
@{
  Layout = "_Layout";
}

@using Factory.Models;
@model List<Factory.Models.Machine>;

<h1>Machines</h1>
<hr/>
@if (@Model.Count == 0)
{
  <h3>There are no machines on to display.</h3>
} 

@foreach (Machine machine in Model)
{
  <h4>@Html.ActionLink($"{machine.MachineName}", "Details", new { id = machine.MachineId })</h4>
}
<hr/>
<p>@Html.ActionLink("Add New Machine", "Create", null, null, new {@class="btn btn-primary"})</p>
<p>@Html.ActionLink("Back Home", "Index", "Home", null, new {@class="btn btn-primary"})</p>